### ISSUE TITLE
Latest Docker Image Fails to Start

### ISSUE THREAD

**Issue by tgregory86** [barrycarey/Speedtest-for-InfluxDB-and-Grafana#17] opened 2019-01-27 16:04 UTC
When running the latest docker image the image fails to run completely, this appears in the logs:

Traceback (most recent call last):
  File "/src/InfluxdbSpeedtest.py", line 9, in <module>
    from influxspeedtest.common import log
ImportError: No module named 'influxspeedtest'
Traceback (most recent call last):
  File "/src/InfluxdbSpeedtest.py", line 9, in <module>
    from influxspeedtest.common import log
ImportError: No module named 'influxspeedtest'
Traceback (most recent call last):
  File "/src/InfluxdbSpeedtest.py", line 9, in <module>
    from influxspeedtest.common import log
ImportError: No module named 'influxspeedtest'

**Comment by bmorris591** [comment] 2019-01-27 17:16
I too have this issue - same error.

**Comment by bmorris591** [comment] 2019-01-27 19:26
It looks to me like the `Dockerfile` hasn't been updated in line with the refactoring and that means that none of the code refactored out into separate files is present in the container.

**Comment by barrycarey** [comment] 2019-01-27 19:46
Try this branch and see if it works: https://github.com/barrycarey/Speedtest-for-InfluxDB-and-Grafana/tree/Issue-17

I have no experience with Docker.  Someone had previously submitted  PR to add support for it.

**Comment by atribe** [comment] 2019-01-27 20:26
That would be me. But you are more than welcome to take over it. All you need to do is get an account on hub.docker.com. Create a repository that is linked to this one and the image will auto create.

But as far as the current issue, it does appear that the correct files are getting into the image. I can roll back my fork to the previous commit to get the previous working image and then fix it later when I have more time. Or @barrycarey you can take over that completely.

**Comment by bmorris591** [comment] 2019-01-27 20:29
It seems that `config.ini` needs a `LOGGING` section - this isn't yet documented. 

Otherwise, works fine - thanks for the speedy response @barrycarey

**Comment by barrycarey** [comment] 2019-01-27 20:54
@bmorris591 That section was added in the update. It's in the default config that comes with the repo


@atribe I updated the Docker file to match the new project structure and it seems to work now.  I'll look into setting it up on Docker Hub.  I've managed to never use Docker.  Probably time to change that.

**Comment by barrycarey** [comment] 2019-01-27 20:58
@bmorris591 I merged the changes back into master.  If everything is good to go please close this issue.

**Comment by atribe** [comment] 2019-01-27 21:01
I'll merge that into my branch so a new image is created.

**Comment by kubax** [comment] 2019-01-27 21:11
i keep getting this error when trying to build the new docker...

```
ERROR: for speedtest  Cannot start service speedtest: b'OCI runtime create failed: container_linux.go:337: starting container process caused "process_linux.go:403: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/srv/docker/Speedtest-for-InfluxDB-and-Grafana/config.ini\\\\\\" to rootfs \\\\\\"/var/lib/docker/btrfs/subvolumes/ad1618499fd03c5d524733b226f12d83931e57fbac89197007416f5824d67777\\\\\\" at \\\\\\"/var/lib/docker/btrfs/subvolumes/ad1618499fd03c5d524733b226f12d83931e57fbac89197007416f5824d67777/src/config.ini\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'
ERROR: Encountered errors while bringing up the project.
```

EDIT: with docker-compose and docker run

EDIT2: Nevermind... seems like docker images got confused... hat to remove all docker images manually, and rebuild it completely.. now it started with the updated version...

**Comment by atribe** [comment] 2019-01-27 21:46
I think the problem is that configparser is not in the requirements.txt

**Comment by kubax** [comment] 2019-01-27 21:47
@atribe 
see my edit above.. seems like it was more of a user problem on my side :)

EDIT: ok, it didn't mount the config file oO

EDIT2: oh boy... i have to learn many things about docker -.- thought when i run docker run -ti IMAGE bash it would also mount the file, but it didn't... seems like everything is working in the container image... at least i got entries in graphana with the updated docker image

**Comment by bmorris591** [comment] 2019-01-28 10:59
@barrycarey not sure I can close this issue - don't think I have the permissions.

I'm happy it's resolved though!

**Closed as completed** 2019-01-29 14:31 UTC
